### ISSUE TITLE
Authentication issue for first time user

### ISSUE THREAD

**Issue by pythonpanda2** [materials-data-facility/forge#52]
I was going through the  Programmatic Interface  steps  **1-3** in the  MDF homepage  https://materialsdatafacility.org/

```

from mdf_forge.forge import Forge
mdf = Forge()
```
As a first time user for me, the MDF_Forge authentication failed when i tried to authenticate via orcid id. But the second time the authentication worked.  May be this issue has to be documented somewhere. 
 
In the step three, the mdf method call has changed. 

```
Old                ---------->     New
mdf.get_globus     ----------->  mdf.globus_download
mdf.get_https(r)   ------------> mdf.http_download(r[0]) 
```

**Comment by jgaff** [comment]
Could you tell us a little more about how the authentication failed the first time? What part failed, and was there an error message?

**Comment by pythonpanda2** [comment]
After logging in with orocid id the page redirected to globus
authentication failed.

**Comment by jgaff** [comment]
It sounds like Globus Auth (which Forge requires) wasn't able to authenticate you with your ORCID the first time, then. Since you were able to authenticate successfully after retrying, it might have been a temporary issue.

**Comment by pythonpanda2** [comment]
We had a mini-GL hackathon this afternoon to go through the repos and
uncover issues. This was one of them . In addition to the changes in the
mdf method calls .
